---
title: "TRNA Protein Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ggplot2)
library(gtools)
library(stringr)
library(cowplot)
library(readxl)
SAVE_FIGS <- FALSE

cbPalette <- c("#CC79A7", "#56B4E9", "#E69F00", "#F0E442", "#0072B2", "#D55E00", "#009E73", "#999999")

# These are genes that are not included in the simulation and should be removed before comparing
# simulations with experimental data
IGNORE_GENES <- c("gene 10B",
                "possible gene 5.5-5.7",
                "gene 1.5",
                "gene 1.6",
                "gene 4.1",
                "gene 4B",
                "gene 0.6A",
                "gene 0.6B",
                "possible gene 0.6B",
                "gene 0.5",
                "gene 0.4")
```

```{r}
id_map <- read_csv("id_map.csv") %>% filter(!is.na(gene_number), !(pinetree %in% IGNORE_GENES))
gene_labels <- unique(mixedsort(id_map$gene_number))
id_map
```

```{r}
labels <- read_csv("id_map.csv") %>% filter(!is.na(gene_number))
load_sim <- function(path) {
  read_tsv(path) %>% group_by(time) %>%
    mutate(time = round(time))
}

#data <- load_sim("data/simulation/phage/old_phage_wildtype.tsv")
base_dir <- "../data/simulation/revised_weighted_opt1.0_nonopt0.22/"
seeds <- c(70, 38, 79, 4, 80, 84, 27, 33, 7, 51)
w_data <- NULL
for (seed in seeds) {
  seed_data <- NULL
    for (fop in c(0.1, 0.7)) {
      tmp <- load_sim(paste0(base_dir,"weighted_opt1.0_nonopt0.22_",seed,"_fop",fop,".tsv"))
      tmp <- tmp %>%mutate(fop = fop)
      if (is.null(seed_data)) {
        seed_data <- tmp
      }
      else {
        seed_data <- rbind(seed_data, tmp)
      }
    seed_data <- seed_data %>% mutate(seed = seed)
    if (is.null(w_data)) {
        w_data <- seed_data
      }
      else {
        w_data <- rbind(w_data, seed_data)
    }
    }
}
```

```{r}
w_data <- w_data %>% 
  group_by(species, time, fop) %>% 
  summarize(protein = mean(protein)) %>%
  mutate(type = "static")
w_data
```


```{r}
#data <- load_sim("data/simulation/phage/old_phage_wildtype.tsv")
base_dir <- "../data/simulation/revised_dynamic_pref0.7_charge0.5_ribospeed1.5/"
seeds <- c(70, 38, 79, 4, 80, 84, 27, 33, 7, 51)
d_data <- NULL
for (seed in seeds) {
  seed_data <- NULL
    for (fop in c(0.1, 0.7)) {
      tmp <- load_sim(paste0(base_dir,"trna_phage_pref0.7_",seed,"_fop",fop,"_ribospeed1.5_trna50000.tsv"))
      tmp <- tmp %>%mutate(fop = fop)
      if (is.null(seed_data)) {
        seed_data <- tmp
      }
      else {
        seed_data <- rbind(seed_data, tmp)
      }
    seed_data <- seed_data %>% mutate(seed = seed)
    if (is.null(d_data)) {
        d_data <- seed_data
      }
      else {
        d_data <- rbind(d_data, seed_data)
    }
    }
}
```

```{r}
d_data <- d_data %>% 
  group_by(species, time, fop) %>% 
  summarize(protein = mean(protein)) %>%
  mutate(type = "dynamic")
```

```{r}
all <- rbind(d_data, w_data)
```

```{r}
ggplot(all%>%filter(species == "bound_ribosome"), aes(x = time, y = protein, color = type)) +
  facet_wrap(~fop) +
  geom_line()
```

```{r}
ggplot(all%>%filter(species == "bound_ribosome", type=="dynamic"), aes(x = time, y = protein, color = as.factor(fop))) +
  geom_line() +
  scale_y_continuous(trans="log10")
```


